import type { PolicyCategorySlug } from './categories';
import type { IPolicyQuestion } from '../models/Policy';

/** Category questionnaires — realistic fields insurers typically ask in Pakistan. */
export const CATEGORY_QUESTION_TEMPLATES: Record<PolicyCategorySlug, IPolicyQuestion[]> = {
  home: [
    {
      id: 'property_type',
      text: 'What type of property are you insuring?',
      type: 'single',
      options: ['Apartment', 'Independent house', 'Villa', 'Commercial unit'],
      required: true,
    },
    {
      id: 'occupancy',
      text: 'How is the property occupied?',
      type: 'single',
      options: ['Owner occupied', 'Rented out', 'Vacant / under construction'],
      required: true,
    },
    {
      id: 'property_value_pkr',
      text: 'Estimated rebuild / property value (PKR)?',
      type: 'number',
      required: true,
    },
    {
      id: 'contents_cover',
      text: 'Do you need contents coverage inside the property?',
      type: 'single',
      options: ['Yes — full contents', 'Yes — limited contents', 'Structure only'],
      required: true,
    },
    {
      id: 'city',
      text: 'City where the property is located?',
      type: 'text',
      required: true,
    },
    {
      id: 'ownership_status',
      text: 'Do you own or rent this property?',
      type: 'single',
      options: ['Owner', 'Tenant', 'Family-owned', 'Company-provided'],
      required: false,
    },
    {
      id: 'construction_type',
      text: 'What is the main construction type?',
      type: 'single',
      options: ['RCC / concrete', 'Brick / cement', 'Mixed construction', 'Other'],
      required: false,
    },
    {
      id: 'security_features',
      text: 'Which security features are installed?',
      type: 'single',
      options: ['Guarded building / society', 'CCTV or alarm', 'Secure locks only', 'No special security'],
      required: false,
    },
    {
      id: 'risk_area',
      text: 'Is the property exposed to flood, fire, or high-theft risk?',
      type: 'single',
      options: ['No known risk', 'Flood / rainwater risk', 'Fire / electrical risk', 'High-theft area'],
      required: false,
    },
    {
      id: 'previous_home_claims',
      text: 'Any home insurance claim in the last 3 years?',
      type: 'single',
      options: ['No', 'Yes — one claim', 'Yes — multiple claims'],
      required: false,
    },
    {
      id: 'owns_vehicle',
      text: 'Do you own a car or motorcycle that may need insurance too?',
      type: 'single',
      options: ['Yes — car', 'Yes — motorcycle', 'Yes — both', 'No'],
      required: false,
    },
    {
      id: 'has_pet',
      text: 'Do you have a pet at home?',
      type: 'single',
      options: ['Dog', 'Cat', 'Other pet', 'No'],
      required: false,
    },
    {
      id: 'family_dependents',
      text: 'Do you financially support family members?',
      type: 'single',
      options: ['No', 'Yes — spouse/parents', 'Yes — children', 'Yes — multiple dependents'],
      required: false,
    },
  ],
  auto: [
    {
      id: 'vehicle_type',
      text: 'What type of vehicle do you want to insure?',
      type: 'single',
      options: ['Private car', 'SUV / 4x4', 'Motorcycle', 'Commercial vehicle'],
      required: true,
    },
    {
      id: 'vehicle_year',
      text: 'Vehicle manufacturing year?',
      type: 'number',
      required: true,
    },
    {
      id: 'vehicle_make_model',
      text: 'Make and model (e.g. Toyota Corolla 2020)?',
      type: 'text',
      required: true,
    },
    {
      id: 'registration_city',
      text: 'Registration city?',
      type: 'single',
      options: ['Karachi', 'Lahore', 'Islamabad / Rawalpindi', 'Other'],
      required: true,
    },
    {
      id: 'coverage_type',
      text: 'Preferred coverage level?',
      type: 'single',
      options: ['Comprehensive', 'Third-party only', 'Third-party + theft'],
      required: true,
    },
    {
      id: 'annual_mileage_km',
      text: 'Approximate annual mileage (km)?',
      type: 'number',
      required: true,
    },
    {
      id: 'vehicle_value_pkr',
      text: 'Current estimated market value of the vehicle (PKR)?',
      type: 'number',
      required: false,
    },
    {
      id: 'vehicle_use',
      text: 'How is the vehicle mostly used?',
      type: 'single',
      options: ['Personal commute', 'Family use', 'Ride-hailing / delivery', 'Business / commercial'],
      required: false,
    },
    {
      id: 'tracker_installed',
      text: 'Is a tracker installed?',
      type: 'single',
      options: ['Yes', 'No', 'Planned before policy starts'],
      required: false,
    },
    {
      id: 'driver_age_band',
      text: 'Primary driver age group?',
      type: 'single',
      options: ['Under 25', '25–35', '36–50', '50+'],
      required: false,
    },
    {
      id: 'previous_auto_claims',
      text: 'Any motor claim or accident in the last 3 years?',
      type: 'single',
      options: ['No', 'Yes — minor', 'Yes — major', 'Prefer not to say'],
      required: false,
    },
    {
      id: 'financed_vehicle',
      text: 'Is the vehicle bank-financed or leased?',
      type: 'single',
      options: ['No', 'Yes — bank financed', 'Yes — leased/company car'],
      required: false,
    },
    {
      id: 'home_owner',
      text: 'Do you own or rent a home that may need protection?',
      type: 'single',
      options: ['Own home', 'Rent home', 'Family home', 'No fixed property need'],
      required: false,
    },
    {
      id: 'has_pet',
      text: 'Do you travel with pets or own a pet?',
      type: 'single',
      options: ['Yes', 'No'],
      required: false,
    },
  ],
  life: [
    {
      id: 'coverage_goal',
      text: 'What is your primary coverage goal?',
      type: 'single',
      options: [
        'Family income protection',
        'Children education fund',
        'Mortgage / loan protection',
        'Retirement planning',
      ],
      required: true,
    },
    {
      id: 'age_band',
      text: 'Your age group?',
      type: 'single',
      options: ['18–30', '31–40', '41–50', '51–60', '60+'],
      required: true,
    },
    {
      id: 'annual_income_pkr',
      text: 'Annual income (PKR)?',
      type: 'number',
      required: true,
    },
    {
      id: 'dependents',
      text: 'Number of dependents to cover?',
      type: 'single',
      options: ['None', '1–2', '3–4', '5 or more'],
      required: true,
    },
    {
      id: 'smoker',
      text: 'Do you use tobacco products?',
      type: 'single',
      options: ['No', 'Yes — occasionally', 'Yes — regularly'],
      required: true,
    },
    {
      id: 'health_condition',
      text: 'Any major pre-existing medical condition?',
      type: 'single',
      options: ['No', 'Diabetes / blood pressure', 'Heart / respiratory condition', 'Other condition'],
      required: false,
    },
    {
      id: 'occupation_risk',
      text: 'Occupation risk level?',
      type: 'single',
      options: ['Office / desk job', 'Field work', 'Industrial / factory', 'High-risk duty'],
      required: false,
    },
    {
      id: 'existing_life_cover',
      text: 'Do you already have life insurance?',
      type: 'single',
      options: ['No', 'Yes — employer provided', 'Yes — personal policy', 'Not sure'],
      required: false,
    },
    {
      id: 'monthly_budget_pkr',
      text: 'Comfortable monthly premium budget (PKR)?',
      type: 'number',
      required: false,
    },
    {
      id: 'owns_vehicle',
      text: 'Do you own a car or motorcycle?',
      type: 'single',
      options: ['Car', 'Motorcycle', 'Both', 'No'],
      required: false,
    },
    {
      id: 'home_owner',
      text: 'Do you own or rent your home?',
      type: 'single',
      options: ['Own', 'Rent', 'Family home', 'Other'],
      required: false,
    },
    {
      id: 'has_pet',
      text: 'Do you own a pet?',
      type: 'single',
      options: ['Dog', 'Cat', 'Other pet', 'No'],
      required: false,
    },
  ],
  pet: [
    {
      id: 'pet_type',
      text: 'What type of pet do you have?',
      type: 'single',
      options: ['Dog', 'Cat', 'Bird', 'Other'],
      required: true,
    },
    {
      id: 'pet_breed',
      text: 'Breed or description?',
      type: 'text',
      required: true,
    },
    {
      id: 'pet_age_years',
      text: 'Pet age (years)?',
      type: 'number',
      required: true,
    },
    {
      id: 'pet_weight_kg',
      text: 'Approximate weight (kg)?',
      type: 'number',
      required: true,
    },
    {
      id: 'vaccination_status',
      text: 'Vaccination status?',
      type: 'single',
      options: ['Fully vaccinated', 'Partially vaccinated', 'Not vaccinated yet'],
      required: true,
    },
    {
      id: 'pre_existing_conditions',
      text: 'Any pre-existing health conditions?',
      type: 'single',
      options: ['No', 'Yes — minor/controlled', 'Yes — major/chronic', 'Not sure'],
      required: false,
    },
    {
      id: 'vet_visit_frequency',
      text: 'How often do you visit a vet?',
      type: 'single',
      options: ['Only emergencies', '1–2 times a year', 'Every few months', 'Monthly or more'],
      required: false,
    },
    {
      id: 'pet_lifestyle',
      text: 'Pet lifestyle?',
      type: 'single',
      options: ['Indoor only', 'Outdoor mostly', 'Both indoor and outdoor', 'Travels frequently'],
      required: false,
    },
    {
      id: 'pet_value_pkr',
      text: 'Estimated pet value or adoption cost (PKR)?',
      type: 'number',
      required: false,
    },
    {
      id: 'home_owner',
      text: 'Do you own or rent your home?',
      type: 'single',
      options: ['Own', 'Rent', 'Family home', 'Other'],
      required: false,
    },
    {
      id: 'owns_vehicle',
      text: 'Do you use a car/motorcycle for pet travel?',
      type: 'single',
      options: ['Car', 'Motorcycle', 'Both', 'No'],
      required: false,
    },
  ],
};
