import type { PolicyCategorySlug } from '../constants/categories';
import type { PolicyStatus } from '../constants/policyStatus';
import type { IPolicyQuestion } from '../models/Policy';

export interface SeedPolicyRecord {
  seedKey: string;
  insurerSeedKey: string;
  slug: string;
  name: string;
  category: PolicyCategorySlug;
  description: string;
  premiumMonthlyPkr: number;
  premiumYearlyPkr: number;
  coverageSummary: string;
  features: string[];
  deductiblePkr: number;
  questions: IPolicyQuestion[];
  status: PolicyStatus;
  rejectionReason?: string;
}

const homeQuestions: IPolicyQuestion[] = [
  {
    id: 'property_type',
    text: 'What type of property do you want to insure?',
    type: 'single',
    options: ['Apartment', 'Independent house', 'Villa'],
    required: true,
  },
  {
    id: 'property_value_pkr',
    text: 'Estimated property value (PKR)?',
    type: 'number',
    required: true,
  },
];

const autoQuestions: IPolicyQuestion[] = [
  {
    id: 'vehicle_type',
    text: 'What type of vehicle do you drive?',
    type: 'single',
    options: ['Car', 'Motorcycle', 'SUV'],
    required: true,
  },
  {
    id: 'vehicle_year',
    text: 'Vehicle manufacturing year?',
    type: 'number',
    required: true,
  },
];

const lifeQuestions: IPolicyQuestion[] = [
  {
    id: 'coverage_goal',
    text: 'Primary coverage goal?',
    type: 'single',
    options: ['Family protection', 'Education fund', 'Retirement planning'],
    required: true,
  },
  {
    id: 'annual_income_pkr',
    text: 'Annual income (PKR)?',
    type: 'number',
    required: true,
  },
];

const petQuestions: IPolicyQuestion[] = [
  {
    id: 'pet_type',
    text: 'What type of pet do you have?',
    type: 'single',
    options: ['Dog', 'Cat', 'Other'],
    required: true,
  },
  {
    id: 'pet_age_years',
    text: 'Pet age in years?',
    type: 'number',
    required: true,
  },
];

export const SEED_POLICIES: SeedPolicyRecord[] = [
  // Home — 4 policies
  {
    seedKey: 'tpl-home-essential',
    insurerSeedKey: 'tpl',
    slug: 'tpl-home-essential',
    name: 'TPL Home Essential',
    category: 'home',
    description: 'Basic fire and theft cover for apartments and small homes in major Pakistani cities.',
    premiumMonthlyPkr: 3500,
    premiumYearlyPkr: 39900,
    coverageSummary: 'Up to PKR 5,000,000 building cover with theft add-on.',
    features: [
      'Fire & lightning cover',
      'Theft & burglary protection',
      '24/7 Karachi/Lahore helpline',
      'Fast cashless claims desk',
      'Optional electronics bundle',
    ],
    deductiblePkr: 25000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-home-shield',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-home-shield',
    name: 'Jubilee Home Shield',
    category: 'home',
    description: 'Comprehensive home plan with natural disaster rider for Lahore and Islamabad.',
    premiumMonthlyPkr: 5200,
    premiumYearlyPkr: 59280,
    coverageSummary: 'Up to PKR 8,000,000 combined building and contents.',
    features: ['Flood rider', 'Contents cover', 'Temporary accommodation'],
    deductiblePkr: 35000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-home-plus',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-home-plus',
    name: 'Adamjee Home Plus',
    category: 'home',
    description: 'Flexible home insurance for independent houses with optional electronics cover.',
    premiumMonthlyPkr: 4800,
    premiumYearlyPkr: 54720,
    coverageSummary: 'Up to PKR 7,500,000 building with optional electronics bundle.',
    features: ['Electronics add-on', 'Burglary cover', 'Fast claims desk'],
    deductiblePkr: 30000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'tpl-home-premium',
    insurerSeedKey: 'tpl',
    slug: 'tpl-home-premium',
    name: 'TPL Home Premium (Pending)',
    category: 'home',
    description: 'Premium villa package awaiting admin approval for demo workflows.',
    premiumMonthlyPkr: 8900,
    premiumYearlyPkr: 101460,
    coverageSummary: 'Up to PKR 15,000,000 villa cover with concierge claims.',
    features: ['Concierge claims', 'Garden structures', 'Guest house cover'],
    deductiblePkr: 50000,
    questions: homeQuestions,
    status: 'pending',
  },

  // Auto — 4 policies
  {
    seedKey: 'tpl-auto-comprehensive',
    insurerSeedKey: 'tpl',
    slug: 'tpl-auto-comprehensive',
    name: 'TPL Auto Comprehensive',
    category: 'auto',
    description: 'Full motor cover for sedans and hatchbacks with nationwide workshop network.',
    premiumMonthlyPkr: 6200,
    premiumYearlyPkr: 70680,
    coverageSummary: 'Own damage plus third-party liability up to PKR 2,000,000.',
    features: [
      'Own damage & total loss',
      'Third-party liability up to PKR 2M',
      'Windscreen & glass cover',
      'Nationwide workshop network',
      'Courtesy car for 5 days',
    ],
    deductiblePkr: 20000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-auto-guard',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-auto-guard',
    name: 'Jubilee Auto Guard',
    category: 'auto',
    description: 'Popular motor plan for family SUVs with roadside assistance in Punjab.',
    premiumMonthlyPkr: 7800,
    premiumYearlyPkr: 88920,
    coverageSummary: 'Comprehensive SUV cover up to PKR 4,500,000 vehicle value.',
    features: ['Roadside assistance', 'Replacement car', 'Theft cover'],
    deductiblePkr: 25000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-auto-smart',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-auto-smart',
    name: 'Adamjee Auto Smart',
    category: 'auto',
    description: 'Budget-friendly motor Takaful-style plan for daily commuters.',
    premiumMonthlyPkr: 4100,
    premiumYearlyPkr: 46740,
    coverageSummary: 'Third-party plus limited own damage up to PKR 1,500,000.',
    features: ['Affordable premium', 'Quick renewal', 'Digital policy card'],
    deductiblePkr: 15000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-auto-fleet',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-auto-fleet',
    name: 'Jubilee Auto Fleet (Pending)',
    category: 'auto',
    description: 'Small business fleet package pending employee approval.',
    premiumMonthlyPkr: 12500,
    premiumYearlyPkr: 142500,
    coverageSummary: 'Multi-vehicle fleet cover for up to 5 commercial vehicles.',
    features: ['Fleet dashboard', 'Driver training discount', 'Bulk renewal'],
    deductiblePkr: 40000,
    questions: autoQuestions,
    status: 'pending',
  },

  // Life — 4 policies
  {
    seedKey: 'jubilee-life-family',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-life-family',
    name: 'Jubilee Life Family Plan',
    category: 'life',
    description: 'Term life protection designed for young families in urban Pakistan.',
    premiumMonthlyPkr: 2800,
    premiumYearlyPkr: 31920,
    coverageSummary: 'PKR 3,000,000 sum assured with optional critical illness rider.',
    features: ['Critical illness rider', 'Monthly payout option', 'Sharia-compliant option'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-life-secure',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-life-secure',
    name: 'Adamjee Life Secure',
    category: 'life',
    description: 'Whole life plan with education benefit for children.',
    premiumMonthlyPkr: 4500,
    premiumYearlyPkr: 51300,
    coverageSummary: 'PKR 5,000,000 life cover with education milestone bonuses.',
    features: ['Education bonus', 'Maturity benefit', 'Premium waiver'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'tpl-life-term',
    insurerSeedKey: 'tpl',
    slug: 'tpl-life-term',
    name: 'TPL Life Term 20',
    category: 'life',
    description: 'Affordable 20-year term life cover with simple underwriting.',
    premiumMonthlyPkr: 2200,
    premiumYearlyPkr: 25080,
    coverageSummary: 'PKR 2,500,000 term cover for ages 25–50.',
    features: ['Simple underwriting', 'Online nomination', 'Tax documentation support'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-life-wealth',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-life-wealth',
    name: 'Adamjee Life Wealth (Pending)',
    category: 'life',
    description: 'Investment-linked life plan awaiting compliance review.',
    premiumMonthlyPkr: 9500,
    premiumYearlyPkr: 108300,
    coverageSummary: 'PKR 10,000,000 cover/universal life hybrid.',
    features: ['Fund switching', 'Partial withdrawal', 'Wealth advisor access'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'pending',
  },

  // Pet — 4 policies
  {
    seedKey: 'tpl-pet-care',
    insurerSeedKey: 'tpl',
    slug: 'tpl-pet-care',
    name: 'TPL Pet Care Basic',
    category: 'pet',
    description: 'Veterinary expense cover for dogs and cats in Karachi and Lahore.',
    premiumMonthlyPkr: 1800,
    premiumYearlyPkr: 20520,
    coverageSummary: 'Up to PKR 150,000 annual vet bills with accident cover.',
    features: ['Accident cover', 'Vaccination allowance', 'Partner clinic network'],
    deductiblePkr: 5000,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-pet-shield',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-pet-shield',
    name: 'Jubilee Pet Shield',
    category: 'pet',
    description: 'Enhanced pet plan with surgery and hospitalization benefits.',
    premiumMonthlyPkr: 2600,
    premiumYearlyPkr: 29640,
    coverageSummary: 'Up to PKR 250,000 vet cover including surgery.',
    features: ['Surgery cover', 'Hospitalization', 'Lost pet poster support'],
    deductiblePkr: 7500,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-pet-plus',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-pet-plus',
    name: 'Adamjee Pet Plus',
    category: 'pet',
    description: 'Wellness-focused pet insurance with annual check-up allowance.',
    premiumMonthlyPkr: 2100,
    premiumYearlyPkr: 23940,
    coverageSummary: 'Up to PKR 200,000 combined accident and wellness cover.',
    features: ['Wellness visits', 'Dental cleaning', 'Tele-vet consults'],
    deductiblePkr: 6000,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'tpl-pet-premium',
    insurerSeedKey: 'tpl',
    slug: 'tpl-pet-premium',
    name: 'TPL Pet Premium (Pending)',
    category: 'pet',
    description: 'Premium exotic pet cover pending admin approval.',
    premiumMonthlyPkr: 4200,
    premiumYearlyPkr: 47880,
    coverageSummary: 'Up to PKR 400,000 cover for exotic breeds and birds.',
    features: ['Exotic breed cover', 'Specialist vet network', 'Emergency transport'],
    deductiblePkr: 10000,
    questions: petQuestions,
    status: 'pending',
  },

  // Additional approved catalog — motorcycle, pet variants, and richer home cover
  {
    seedKey: 'tpl-motorcycle-ride',
    insurerSeedKey: 'tpl',
    slug: 'tpl-motorcycle-ride',
    name: 'TPL Motorcycle Ride',
    category: 'auto',
    description:
      'Dedicated motorcycle Takaful for daily commuters in Karachi, Lahore, and Islamabad with roadside recovery.',
    premiumMonthlyPkr: 1850,
    premiumYearlyPkr: 21090,
    coverageSummary: 'Third-party plus own damage up to PKR 350,000 for motorcycles up to 250cc.',
    features: [
      'Helmet & riding gear allowance',
      'Roadside towing in major cities',
      'Theft cover with GPS discount',
      'Accident medical expenses',
      'Digital policy card',
    ],
    deductiblePkr: 8000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-bike-pro',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-bike-pro',
    name: 'Jubilee Bike Pro',
    category: 'auto',
    description:
      'Popular Jubilee motorbike plan with partner workshops across Punjab and Sindh.',
    premiumMonthlyPkr: 2200,
    premiumYearlyPkr: 25080,
    coverageSummary: 'Comprehensive bike cover up to PKR 500,000 with passenger liability.',
    features: [
      'Passenger liability included',
      'Partner workshop repairs',
      'New-for-old parts under 2 years',
      'Hit-and-run protection',
      'WhatsApp claims support',
    ],
    deductiblePkr: 10000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'adamjee-bike-cover',
    insurerSeedKey: 'adamjee',
    slug: 'adamjee-bike-cover',
    name: 'Adamjee Bike Cover',
    category: 'auto',
    description:
      'Budget bike insurance for students and delivery riders with simple documentation.',
    premiumMonthlyPkr: 1600,
    premiumYearlyPkr: 18240,
    coverageSummary: 'Third-party liability plus limited own damage up to PKR 250,000.',
    features: [
      'Low premium for 125–150cc bikes',
      'CNIC-only onboarding',
      'Theft cover in gated parking',
      'Accident hospital cash benefit',
    ],
    deductiblePkr: 7000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'tpl-dog-guard',
    insurerSeedKey: 'tpl',
    slug: 'tpl-dog-guard',
    name: 'TPL Dog Guard',
    category: 'pet',
    description:
      'Vet expense plan for dogs with annual vaccination and surgery benefits in partner clinics.',
    premiumMonthlyPkr: 2400,
    premiumYearlyPkr: 27360,
    coverageSummary: 'Up to PKR 200,000 annual vet bills for dogs aged 8 weeks–8 years.',
    features: [
      'Annual wellness exam',
      'Surgery & hospitalization',
      'Vaccination allowance',
      'Third-party liability for dogs',
      'Tele-vet consults',
    ],
    deductiblePkr: 6000,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-cat-care',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-cat-care',
    name: 'Jubilee Cat Care',
    category: 'pet',
    description:
      'Indoor and outdoor cat cover with chronic condition support after waiting period.',
    premiumMonthlyPkr: 1950,
    premiumYearlyPkr: 22230,
    coverageSummary: 'Up to PKR 175,000 vet cover per year for cats with microchip discount.',
    features: [
      'Chronic illness cover',
      'Dental cleaning allowance',
      'Lost cat poster support',
      'Emergency boarding',
      'Multi-cat household discount',
    ],
    deductiblePkr: 5500,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'jubilee-home-elite',
    insurerSeedKey: 'jubilee',
    slug: 'jubilee-home-elite',
    name: 'Jubilee Home Elite',
    category: 'home',
    description:
      'Premium villa and farmhouse package with flood, earthquake, and domestic staff liability.',
    premiumMonthlyPkr: 9800,
    premiumYearlyPkr: 111720,
    coverageSummary: 'Up to PKR 20,000,000 building and PKR 3,000,000 contents cover.',
    features: [
      'Flood & rainwater rider',
      'Earthquake structural cover',
      'Domestic staff liability',
      'Temporary relocation expenses',
      'Smart home device cover',
      'Dedicated claims manager',
    ],
    deductiblePkr: 45000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'tpl-auto-third-party',
    insurerSeedKey: 'tpl',
    slug: 'tpl-auto-third-party',
    name: 'TPL Auto Third Party',
    category: 'auto',
    description:
      'Mandatory-style third-party motor cover for older sedans with affordable yearly premium.',
    premiumMonthlyPkr: 2900,
    premiumYearlyPkr: 33060,
    coverageSummary: 'Third-party bodily injury and property damage up to PKR 3,000,000.',
    features: [
      'Legal liability cover',
      'Court bail bond assistance',
      'Instant policy issuance',
      'Renewal reminders',
    ],
    deductiblePkr: 0,
    questions: autoQuestions,
    status: 'approved',
  },

  // HBL — 2 approved per category
  {
    seedKey: 'hbl-home-essential',
    insurerSeedKey: 'hbl',
    slug: 'hbl-home-essential',
    name: 'HBL Home Essential',
    category: 'home',
    description: 'Affordable fire and theft cover for apartments in Karachi and Lahore.',
    premiumMonthlyPkr: 3800,
    premiumYearlyPkr: 43320,
    coverageSummary: 'Up to PKR 6,000,000 building cover with contents add-on.',
    features: ['Fire cover', 'Theft protection', 'Bank-backed claims desk'],
    deductiblePkr: 22000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-home-guard',
    insurerSeedKey: 'hbl',
    slug: 'hbl-home-guard',
    name: 'HBL Home Guard',
    category: 'home',
    description: 'Comprehensive home plan with flood rider for urban villas.',
    premiumMonthlyPkr: 5600,
    premiumYearlyPkr: 63840,
    coverageSummary: 'Up to PKR 10,000,000 combined building and contents.',
    features: ['Flood rider', 'Earthquake add-on', 'Temporary accommodation'],
    deductiblePkr: 32000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-auto-comprehensive',
    insurerSeedKey: 'hbl',
    slug: 'hbl-auto-comprehensive',
    name: 'HBL Auto Comprehensive',
    category: 'auto',
    description: 'Full motor cover with nationwide workshop network.',
    premiumMonthlyPkr: 6500,
    premiumYearlyPkr: 74100,
    coverageSummary: 'Own damage plus third-party liability up to PKR 2,500,000.',
    features: ['Own damage', 'Third-party liability', 'Windscreen cover'],
    deductiblePkr: 18000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-auto-city',
    insurerSeedKey: 'hbl',
    slug: 'hbl-auto-city',
    name: 'HBL Auto City',
    category: 'auto',
    description: 'City commuter plan for sedans with roadside assistance.',
    premiumMonthlyPkr: 4300,
    premiumYearlyPkr: 49020,
    coverageSummary: 'Third-party plus limited own damage up to PKR 1,800,000.',
    features: ['Roadside assistance', 'Quick renewal', 'Digital policy card'],
    deductiblePkr: 12000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-life-family',
    insurerSeedKey: 'hbl',
    slug: 'hbl-life-family',
    name: 'HBL Life Family',
    category: 'life',
    description: 'Term life protection for young families with education rider.',
    premiumMonthlyPkr: 3100,
    premiumYearlyPkr: 35340,
    coverageSummary: 'PKR 4,000,000 sum assured with education milestone bonus.',
    features: ['Education rider', 'Monthly payout option', 'Online nomination'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-life-term',
    insurerSeedKey: 'hbl',
    slug: 'hbl-life-term',
    name: 'HBL Life Term 15',
    category: 'life',
    description: 'Affordable 15-year term cover with simple underwriting.',
    premiumMonthlyPkr: 2400,
    premiumYearlyPkr: 27360,
    coverageSummary: 'PKR 3,000,000 term cover for ages 25–55.',
    features: ['Simple underwriting', 'Tax documentation', 'Premium waiver option'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-pet-care',
    insurerSeedKey: 'hbl',
    slug: 'hbl-pet-care',
    name: 'HBL Pet Care',
    category: 'pet',
    description: 'Veterinary expense cover for dogs and cats in major cities.',
    premiumMonthlyPkr: 1900,
    premiumYearlyPkr: 21660,
    coverageSummary: 'Up to PKR 180,000 annual vet bills with accident cover.',
    features: ['Accident cover', 'Vaccination allowance', 'Partner clinics'],
    deductiblePkr: 5500,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'hbl-pet-plus',
    insurerSeedKey: 'hbl',
    slug: 'hbl-pet-plus',
    name: 'HBL Pet Plus',
    category: 'pet',
    description: 'Enhanced pet plan with surgery and hospitalization benefits.',
    premiumMonthlyPkr: 2700,
    premiumYearlyPkr: 30780,
    coverageSummary: 'Up to PKR 280,000 vet cover including surgery.',
    features: ['Surgery cover', 'Hospitalization', 'Tele-vet consults'],
    deductiblePkr: 7000,
    questions: petQuestions,
    status: 'approved',
  },

  // Allianz — 2 approved per category
  {
    seedKey: 'allianz-home-shield',
    insurerSeedKey: 'allianz',
    slug: 'allianz-home-shield',
    name: 'Allianz Home Shield',
    category: 'home',
    description: 'Premium home protection with natural disaster cover.',
    premiumMonthlyPkr: 5400,
    premiumYearlyPkr: 61560,
    coverageSummary: 'Up to PKR 9,000,000 building and contents cover.',
    features: ['Natural disaster rider', 'Contents cover', 'Smart home devices'],
    deductiblePkr: 34000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-home-elite',
    insurerSeedKey: 'allianz',
    slug: 'allianz-home-elite',
    name: 'Allianz Home Elite',
    category: 'home',
    description: 'Elite villa package with concierge claims service.',
    premiumMonthlyPkr: 9200,
    premiumYearlyPkr: 104880,
    coverageSummary: 'Up to PKR 18,000,000 villa cover with staff liability.',
    features: ['Concierge claims', 'Garden structures', 'Guest house cover'],
    deductiblePkr: 48000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-auto-guard',
    insurerSeedKey: 'allianz',
    slug: 'allianz-auto-guard',
    name: 'Allianz Auto Guard',
    category: 'auto',
    description: 'Comprehensive motor cover for family SUVs and sedans.',
    premiumMonthlyPkr: 7200,
    premiumYearlyPkr: 82080,
    coverageSummary: 'Full comprehensive cover up to PKR 5,000,000 vehicle value.',
    features: ['Replacement car', 'Roadside assistance', 'Theft cover'],
    deductiblePkr: 22000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-auto-premium',
    insurerSeedKey: 'allianz',
    slug: 'allianz-auto-premium',
    name: 'Allianz Auto Premium',
    category: 'auto',
    description: 'Luxury vehicle cover with international assistance.',
    premiumMonthlyPkr: 11800,
    premiumYearlyPkr: 134520,
    coverageSummary: 'Premium cover up to PKR 12,000,000 for imported vehicles.',
    features: ['International assistance', 'Agency repairs', 'Zero depreciation option'],
    deductiblePkr: 35000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-life-secure',
    insurerSeedKey: 'allianz',
    slug: 'allianz-life-secure',
    name: 'Allianz Life Secure',
    category: 'life',
    description: 'Whole life plan with critical illness rider.',
    premiumMonthlyPkr: 4800,
    premiumYearlyPkr: 54720,
    coverageSummary: 'PKR 6,000,000 life cover with critical illness benefit.',
    features: ['Critical illness rider', 'Maturity benefit', 'Premium waiver'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-life-wealth',
    insurerSeedKey: 'allianz',
    slug: 'allianz-life-wealth',
    name: 'Allianz Life Wealth',
    category: 'life',
    description: 'Investment-linked life plan for wealth accumulation.',
    premiumMonthlyPkr: 8800,
    premiumYearlyPkr: 100320,
    coverageSummary: 'PKR 8,000,000 cover with fund switching options.',
    features: ['Fund switching', 'Partial withdrawal', 'Wealth advisor access'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-pet-shield',
    insurerSeedKey: 'allianz',
    slug: 'allianz-pet-shield',
    name: 'Allianz Pet Shield',
    category: 'pet',
    description: 'Comprehensive pet insurance with chronic condition support.',
    premiumMonthlyPkr: 2500,
    premiumYearlyPkr: 28500,
    coverageSummary: 'Up to PKR 260,000 vet cover per year.',
    features: ['Chronic illness cover', 'Dental cleaning', 'Emergency boarding'],
    deductiblePkr: 6500,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'allianz-pet-care',
    insurerSeedKey: 'allianz',
    slug: 'allianz-pet-care',
    name: 'Allianz Pet Care',
    category: 'pet',
    description: 'Wellness-focused pet plan with annual check-up allowance.',
    premiumMonthlyPkr: 2000,
    premiumYearlyPkr: 22800,
    coverageSummary: 'Up to PKR 190,000 combined accident and wellness cover.',
    features: ['Wellness visits', 'Vaccination allowance', 'Multi-pet discount'],
    deductiblePkr: 5000,
    questions: petQuestions,
    status: 'approved',
  },

  // EFU Life — 2 approved per category
  {
    seedKey: 'efu-home-plus',
    insurerSeedKey: 'efu',
    slug: 'efu-home-plus',
    name: 'EFU Home Plus',
    category: 'home',
    description: 'Flexible home insurance for independent houses in Punjab.',
    premiumMonthlyPkr: 4600,
    premiumYearlyPkr: 52440,
    coverageSummary: 'Up to PKR 7,000,000 building with electronics bundle.',
    features: ['Electronics bundle', 'Burglary cover', 'Fast claims desk'],
    deductiblePkr: 28000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-home-premium',
    insurerSeedKey: 'efu',
    slug: 'efu-home-premium',
    name: 'EFU Home Premium',
    category: 'home',
    description: 'Premium farmhouse and villa package with flood cover.',
    premiumMonthlyPkr: 8500,
    premiumYearlyPkr: 96900,
    coverageSummary: 'Up to PKR 14,000,000 building and contents.',
    features: ['Flood cover', 'Domestic staff liability', 'Temporary relocation'],
    deductiblePkr: 42000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-auto-smart',
    insurerSeedKey: 'efu',
    slug: 'efu-auto-smart',
    name: 'EFU Auto Smart',
    category: 'auto',
    description: 'Budget-friendly motor plan for daily commuters.',
    premiumMonthlyPkr: 3900,
    premiumYearlyPkr: 44460,
    coverageSummary: 'Third-party plus limited own damage up to PKR 1,600,000.',
    features: ['Affordable premium', 'Digital policy card', 'Quick renewal'],
    deductiblePkr: 14000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-auto-suv',
    insurerSeedKey: 'efu',
    slug: 'efu-auto-suv',
    name: 'EFU Auto SUV',
    category: 'auto',
    description: 'SUV-focused motor cover with family passenger liability.',
    premiumMonthlyPkr: 8100,
    premiumYearlyPkr: 92340,
    coverageSummary: 'Comprehensive SUV cover up to PKR 4,800,000.',
    features: ['Passenger liability', 'Courtesy car', 'Nationwide workshops'],
    deductiblePkr: 24000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-life-education',
    insurerSeedKey: 'efu',
    slug: 'efu-life-education',
    name: 'EFU Life Education',
    category: 'life',
    description: 'Education-focused life plan for children\'s future expenses.',
    premiumMonthlyPkr: 3600,
    premiumYearlyPkr: 41040,
    coverageSummary: 'PKR 4,500,000 cover with education milestone payouts.',
    features: ['Education milestones', 'Premium waiver', 'Tax benefits'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-life-retirement',
    insurerSeedKey: 'efu',
    slug: 'efu-life-retirement',
    name: 'EFU Life Retirement',
    category: 'life',
    description: 'Retirement planning with monthly annuity option.',
    premiumMonthlyPkr: 5200,
    premiumYearlyPkr: 59280,
    coverageSummary: 'PKR 5,500,000 cover with retirement annuity rider.',
    features: ['Annuity option', 'Maturity benefit', 'Fund switching'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-pet-wellness',
    insurerSeedKey: 'efu',
    slug: 'efu-pet-wellness',
    name: 'EFU Pet Wellness',
    category: 'pet',
    description: 'Wellness-first pet cover with annual vaccination benefits.',
    premiumMonthlyPkr: 1750,
    premiumYearlyPkr: 19950,
    coverageSummary: 'Up to PKR 160,000 vet cover with wellness visits.',
    features: ['Wellness visits', 'Vaccination allowance', 'Tele-vet consults'],
    deductiblePkr: 4500,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-pet-guard',
    insurerSeedKey: 'efu',
    slug: 'efu-pet-guard',
    name: 'EFU Pet Guard',
    category: 'pet',
    description: 'Accident and surgery cover for dogs and cats.',
    premiumMonthlyPkr: 2300,
    premiumYearlyPkr: 26220,
    coverageSummary: 'Up to PKR 220,000 annual vet bills including surgery.',
    features: ['Surgery cover', 'Accident cover', 'Partner clinic network'],
    deductiblePkr: 6000,
    questions: petQuestions,
    status: 'approved',
  },

  // IGI General — 2 approved per category
  {
    seedKey: 'igi-home-basic',
    insurerSeedKey: 'igi',
    slug: 'igi-home-basic',
    name: 'IGI Home Basic',
    category: 'home',
    description: 'Entry-level home cover for apartments and small houses.',
    premiumMonthlyPkr: 3200,
    premiumYearlyPkr: 36480,
    coverageSummary: 'Up to PKR 4,500,000 building cover.',
    features: ['Fire cover', 'Theft protection', '24/7 helpline'],
    deductiblePkr: 20000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-home-comprehensive',
    insurerSeedKey: 'igi',
    slug: 'igi-home-comprehensive',
    name: 'IGI Home Comprehensive',
    category: 'home',
    description: 'Full home package with contents and natural disaster rider.',
    premiumMonthlyPkr: 5900,
    premiumYearlyPkr: 67260,
    coverageSummary: 'Up to PKR 9,500,000 combined building and contents.',
    features: ['Contents cover', 'Flood rider', 'Temporary accommodation'],
    deductiblePkr: 33000,
    questions: homeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-auto-drive',
    insurerSeedKey: 'igi',
    slug: 'igi-auto-drive',
    name: 'IGI Auto Drive',
    category: 'auto',
    description: 'Popular motor plan for sedans with workshop network.',
    premiumMonthlyPkr: 5800,
    premiumYearlyPkr: 66120,
    coverageSummary: 'Comprehensive cover up to PKR 3,500,000 vehicle value.',
    features: ['Own damage', 'Third-party liability', 'Windscreen cover'],
    deductiblePkr: 19000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-auto-fleet-lite',
    insurerSeedKey: 'igi',
    slug: 'igi-auto-fleet-lite',
    name: 'IGI Auto Fleet Lite',
    category: 'auto',
    description: 'Small business fleet cover for up to 3 commercial vehicles.',
    premiumMonthlyPkr: 9800,
    premiumYearlyPkr: 111720,
    coverageSummary: 'Multi-vehicle fleet cover with driver training discount.',
    features: ['Fleet dashboard', 'Bulk renewal', 'Driver training discount'],
    deductiblePkr: 38000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-life-term',
    insurerSeedKey: 'igi',
    slug: 'igi-life-term',
    name: 'IGI Life Term',
    category: 'life',
    description: 'Simple term life cover for working professionals.',
    premiumMonthlyPkr: 2600,
    premiumYearlyPkr: 29640,
    coverageSummary: 'PKR 3,500,000 term cover for ages 22–55.',
    features: ['Simple underwriting', 'Online nomination', 'Sharia-compliant option'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-life-whole',
    insurerSeedKey: 'igi',
    slug: 'igi-life-whole',
    name: 'IGI Life Whole',
    category: 'life',
    description: 'Whole life plan with education benefit for children.',
    premiumMonthlyPkr: 4200,
    premiumYearlyPkr: 47880,
    coverageSummary: 'PKR 4,800,000 life cover with education bonus.',
    features: ['Education bonus', 'Maturity benefit', 'Premium waiver'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-pet-basic',
    insurerSeedKey: 'igi',
    slug: 'igi-pet-basic',
    name: 'IGI Pet Basic',
    category: 'pet',
    description: 'Affordable pet accident cover for dogs and cats.',
    premiumMonthlyPkr: 1650,
    premiumYearlyPkr: 18810,
    coverageSummary: 'Up to PKR 140,000 annual vet bills.',
    features: ['Accident cover', 'Vaccination allowance', 'Partner clinics'],
    deductiblePkr: 4800,
    questions: petQuestions,
    status: 'approved',
  },
  {
    seedKey: 'igi-pet-premium',
    insurerSeedKey: 'igi',
    slug: 'igi-pet-premium',
    name: 'IGI Pet Premium',
    category: 'pet',
    description: 'Premium pet plan with surgery and chronic illness cover.',
    premiumMonthlyPkr: 2900,
    premiumYearlyPkr: 33060,
    coverageSummary: 'Up to PKR 300,000 vet cover including surgery.',
    features: ['Surgery cover', 'Chronic illness', 'Emergency transport'],
    deductiblePkr: 8000,
    questions: petQuestions,
    status: 'approved',
  },

  // Rejected policies — admin review history
  {
    seedKey: 'hbl-commercial-heavy',
    insurerSeedKey: 'hbl',
    slug: 'hbl-commercial-heavy',
    name: 'HBL Commercial Heavy (Rejected)',
    category: 'home',
    description: 'Commercial warehouse cover rejected due to incomplete compliance documentation.',
    premiumMonthlyPkr: 15000,
    premiumYearlyPkr: 171000,
    coverageSummary: 'Commercial property cover up to PKR 50,000,000.',
    features: ['Warehouse cover', 'Business interruption'],
    deductiblePkr: 100000,
    questions: homeQuestions,
    status: 'rejected',
    rejectionReason: 'Missing SECP compliance certificate and incomplete risk assessment for commercial property.',
  },
  {
    seedKey: 'allianz-expat-cover',
    insurerSeedKey: 'allianz',
    slug: 'allianz-expat-cover',
    name: 'Allianz Expat Cover (Rejected)',
    category: 'life',
    description: 'Expatriate life product rejected pending regulatory approval.',
    premiumMonthlyPkr: 12000,
    premiumYearlyPkr: 136800,
    coverageSummary: 'International life cover for Pakistani expatriates.',
    features: ['International coverage', 'Currency hedging'],
    deductiblePkr: 0,
    questions: lifeQuestions,
    status: 'rejected',
    rejectionReason: 'Product requires additional SECP filing for cross-border life insurance offerings.',
  },
  {
    seedKey: 'igi-marine-freight',
    insurerSeedKey: 'igi',
    slug: 'igi-marine-freight',
    name: 'IGI Marine Freight (Rejected)',
    category: 'auto',
    description: 'Marine cargo rider rejected — outside current platform category scope.',
    premiumMonthlyPkr: 8500,
    premiumYearlyPkr: 96900,
    coverageSummary: 'Marine cargo and freight liability cover.',
    features: ['Cargo cover', 'Port liability'],
    deductiblePkr: 50000,
    questions: autoQuestions,
    status: 'rejected',
    rejectionReason: 'Marine freight products are not supported in the current ClearClever category catalog.',
  },
  // Pak Qatar Takaful — partner policies
  {
    seedKey: 'pak-qatar-auto-comprehensive',
    insurerSeedKey: 'pak-qatar',
    slug: 'pak-qatar-auto-comprehensive',
    name: 'Pak Qatar Motor Takaful Comprehensive',
    category: 'auto',
    description: 'Shariah-compliant comprehensive motor Takaful with tracker support for private cars.',
    premiumMonthlyPkr: 8250,
    premiumYearlyPkr: 94050,
    coverageSummary: 'Comprehensive motor Takaful up to PKR 3,600,000 vehicle value.',
    features: ['Islamic Takaful structure', 'Own damage cover', 'Theft protection', 'Tracker optional'],
    deductiblePkr: 22000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'pak-qatar-home-takaful',
    insurerSeedKey: 'pak-qatar',
    slug: 'pak-qatar-home-takaful',
    name: 'Pak Qatar Home Takaful',
    category: 'home',
    description: 'Fire and natural calamity Takaful for apartments and independent houses.',
    premiumMonthlyPkr: 3200,
    premiumYearlyPkr: 36480,
    coverageSummary: 'Building and contents Takaful up to PKR 8,000,000.',
    features: ['Fire cover', 'Flood rider', 'Earthquake optional'],
    deductiblePkr: 15000,
    questions: homeQuestions,
    status: 'approved',
  },
  // Askari Insurance
  {
    seedKey: 'askari-auto-comprehensive',
    insurerSeedKey: 'askari',
    slug: 'askari-auto-comprehensive',
    name: 'Askari Auto Comprehensive',
    category: 'auto',
    description: 'Full motor cover with cashless workshop network in major cities.',
    premiumMonthlyPkr: 5900,
    premiumYearlyPkr: 67260,
    coverageSummary: 'Comprehensive cover up to PKR 2,800,000 with agency repair option.',
    features: ['Cashless repairs', 'Roadside assistance', 'Windscreen cover'],
    deductiblePkr: 18000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'askari-home-shield',
    insurerSeedKey: 'askari',
    slug: 'askari-home-shield',
    name: 'Askari Home Shield',
    category: 'home',
    description: 'Residential property cover for owner-occupied homes.',
    premiumMonthlyPkr: 2800,
    premiumYearlyPkr: 31920,
    coverageSummary: 'Structure and contents up to PKR 6,500,000.',
    features: ['Fire & lightning', 'Theft cover', 'Third-party liability'],
    deductiblePkr: 12000,
    questions: homeQuestions,
    status: 'approved',
  },
  // EFU General
  {
    seedKey: 'efu-general-auto-plus',
    insurerSeedKey: 'efu-general',
    slug: 'efu-general-auto-plus',
    name: 'EFU General Auto Plus',
    category: 'auto',
    description: 'Premium motor plan for imported and locally assembled vehicles.',
    premiumMonthlyPkr: 7100,
    premiumYearlyPkr: 80940,
    coverageSummary: 'Comprehensive motor up to PKR 5,000,000 vehicle value.',
    features: ['Agency repair', 'Replacement car', 'Natural calamities'],
    deductiblePkr: 25000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'efu-general-home-elite',
    insurerSeedKey: 'efu-general',
    slug: 'efu-general-home-elite',
    name: 'EFU General Home Elite',
    category: 'home',
    description: 'High-value home insurance for villas and independent houses.',
    premiumMonthlyPkr: 4500,
    premiumYearlyPkr: 51300,
    coverageSummary: 'Premium home cover up to PKR 15,000,000 rebuild value.',
    features: ['Full peril cover', 'Contents protection', 'Temporary accommodation'],
    deductiblePkr: 20000,
    questions: homeQuestions,
    status: 'approved',
  },
  // UIC Insurance
  {
    seedKey: 'uic-auto-economy',
    insurerSeedKey: 'uic',
    slug: 'uic-auto-economy',
    name: 'UIC Auto Economy',
    category: 'auto',
    description: 'Budget third-party plus limited own-damage motor plan.',
    premiumMonthlyPkr: 3800,
    premiumYearlyPkr: 43320,
    coverageSummary: 'Third-party liability plus limited own damage up to PKR 1,200,000.',
    features: ['Affordable premium', 'Quick issuance', 'Digital policy'],
    deductiblePkr: 12000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'uic-auto-comprehensive',
    insurerSeedKey: 'uic',
    slug: 'uic-auto-comprehensive',
    name: 'UIC Auto Comprehensive',
    category: 'auto',
    description: 'Full comprehensive motor cover with tracker mandatory option.',
    premiumMonthlyPkr: 6500,
    premiumYearlyPkr: 74100,
    coverageSummary: 'Comprehensive motor up to PKR 3,000,000.',
    features: ['Tracker support', 'Theft cover', 'Natural calamities'],
    deductiblePkr: 20000,
    questions: autoQuestions,
    status: 'approved',
  },
  // Premier Insurance
  {
    seedKey: 'premier-auto-comprehensive',
    insurerSeedKey: 'premier',
    slug: 'premier-auto-comprehensive',
    name: 'Premier Auto Comprehensive',
    category: 'auto',
    description: 'Popular comprehensive motor plan featured on comparison platforms.',
    premiumMonthlyPkr: 5500,
    premiumYearlyPkr: 62700,
    coverageSummary: 'Comprehensive cover up to PKR 2,500,000 with optional tracker.',
    features: ['Competitive rate', 'Theft/snatch cover', 'Third-party liability'],
    deductiblePkr: 15000,
    questions: autoQuestions,
    status: 'approved',
  },
  {
    seedKey: 'premier-pet-care',
    insurerSeedKey: 'premier',
    slug: 'premier-pet-care',
    name: 'Premier Pet Care',
    category: 'pet',
    description: 'Affordable pet accident and illness cover for dogs and cats.',
    premiumMonthlyPkr: 1800,
    premiumYearlyPkr: 20520,
    coverageSummary: 'Annual limit PKR 150,000 for accidents and illness.',
    features: ['Accident cover', 'Illness cover', 'Vaccination benefit'],
    deductiblePkr: 5000,
    questions: petQuestions,
    status: 'approved',
  },
];

export const SEED_POLICY_COUNT = SEED_POLICIES.length;

export const SEED_APPROVED_POLICY_COUNT = SEED_POLICIES.filter((p) => p.status === 'approved').length;

export const SEED_PENDING_POLICY_COUNT = SEED_POLICIES.filter((p) => p.status === 'pending').length;

export const SEED_REJECTED_POLICY_COUNT = SEED_POLICIES.filter((p) => p.status === 'rejected').length;
